# Файл:  Makefile
# Автор: Andrew Salo <salo@cs.karelia.ru>
# Дата:  07.09.2004

# Основной Makefile для проекта


# Средство сборки
MAKE	= make


# Сборка всего проекта
all:
	cd src && $(MAKE) all


# Приведение проекта в исходное состояние
clean:
	cd src && $(MAKE) clean


# "Ложные" цели
.PHONY: all clean
